accounts/backends/alipay/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# 
# Copyright 2013 XiaoMaiFeng


__author__ = "ubernostrum "
__repo__ = "https://bitbucket.org/ubernostrum/django-registration/"
__editor__ = "Bicheng Zhang"
__copyright__ = "Copyright 2013, XiaoMaiFeng"



"""
URLconf for registration and activation, using django-registration's
default backend.

If the default behavior of these views is acceptable to you, simply
use a line like this in your root URLconf to set up the default URLs
for registration::

    (r'^accounts/', include('registration.backends.default.urls')),

This will also automatically set up the views in
``django.contrib.auth`` at sensible default locations.

If you'd like to customize registration behavior, feel free to set up
your own URL patterns for these views instead.

"""


from django.conf.urls import patterns
from django.conf.urls import include
from django.conf.urls import url
from django.views.generic.base import TemplateView

from views import ActivationView, RegistrationView


urlpatterns = patterns('',
                       url(r'^activate/complete/$',
                           TemplateView.as_view(template_name='registration/activation_complete.html'),
                           name='registration_activation_complete'),
                       # Activation keys get matched by \w+ instead of the more specific
                       # [a-fA-F0-9]{40} because a bad activation key should still get to the view;
                       # that way it can return a sensible "invalid key" message instead of a
                       # confusing 404.
                       url(r'^activate/(?P<activation_key>\w+)/$',
                           ActivationView.as_view(),
                           name='registration_activate'),
                       url(r'^register/$',
                           RegistrationView.as_view(),
                           name='registration_register'),
                       url(r'^register/complete/$',
                           TemplateView.as_view(template_name='registration/registration_complete.html'),
                           name='registration_complete'),
                       url(r'^register/closed/$',
                           TemplateView.as_view(template_name='registration/registration_closed.html'),
                           name='registration_disallowed'),
                       (r'', include('registration.auth_urls')),
                       )

accounts/urls.py
# -*- coding: utf-8 -*-
# 
# Copyright 2013 XiaoMaiFeng


__author__ = "ubernostrum "
__repo__ = "https://bitbucket.org/ubernostrum/django-registration/"
__editor__ = "Bicheng Zhang"
__copyright__ = "Copyright 2013, XiaoMaiFeng"


"""
Backwards-compatible URLconf for existing django-registration
installs; this allows the standard ``include('registration.urls')`` to
continue working, but that usage is deprecated and will be removed for
django-registration 1.0. For new installs, use
``include('registration.backends.default.urls')``.

"""

import warnings

warnings.warn("include('accounts.urls') is deprecated; use include('registration.backends.default.urls') instead.",
              DeprecationWarning)

from accounts.backends.default.urls import *

home/urls.py
# -*- coding: utf-8 -*-
# 
# Copyright 2013 XiaoMaiFeng


__author__ = "Bicheng Zhang"
__copyright__ = "Copyright 2013, XiaoMaiFeng"



from django.conf.urls import patterns, url

from home import views

urlpatterns = patterns('',
		url(r'^$', views.HomeView.as_view(), name='index'),
		url(r'^term/$', views.TermView.as_view(), name='term'),
		url(r'^privacy/$', views.PrivacyView.as_view(), name='privacy'),
)

xiaomaifeng/urls.py
# -*- coding: utf-8 -*-
# 
# Copyright 2013 XiaoMaiFeng


__author__ = "Bicheng Zhang"
__copyright__ = "Copyright 2013, XiaoMaiFeng"

from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'jifu.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
	url(r'^', include('home.urls', namespace='home')), 
	url(r'^accounts/', include('accounts.backends.default.urls', namespace='accounts')),
	url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
	url(r'^platforms/', include('platforms.urls', namespace='platforms')), 
	url(r'^payment/', include('payment.urls', namespace='payment')),
)


if settings.DEBUG:
	# static files (images, css, javascript, etc.)
	urlpatterns += patterns('',
    	(r'^(?P<path>.*)$', 'django.views.static.serve', {
    	'document_root': settings.MEDIA_ROOT})
    )

if "notification" in settings.INSTALLED_APPS:
	urlpatterns += patterns('', 
		url(r'^notification/', include('notification.urls', namespace='notification')),
	)

accounts/backends/alipay/views.py
# -*- coding: utf-8 -*-
# 
# Copyright 2013 XiaoMaiFeng


__author__ = "ubernostrum "
__repo__ = "https://bitbucket.org/ubernostrum/django-registration/"
__editor__ = "Bicheng Zhang"
__copyright__ = "Copyright 2013, XiaoMaiFeng"


from django.conf import settings
from django.contrib.sites.models import RequestSite
from django.contrib.sites.models import Site

from registration import signals
from registration.models import RegistrationProfile
from registration.views import ActivationView as BaseActivationView
from registration.views import RegistrationView as BaseRegistrationView


class RegistrationView(BaseRegistrationView):
    """
    A registration backend which follows a simple workflow:

    1. User signs up, inactive account is created.

    2. Email is sent to user with activation link.

    3. User clicks activation link, account is now active.

    Using this backend requires that

    * ``registration`` be listed in the ``INSTALLED_APPS`` setting
      (since this backend makes use of models defined in this
      application).

    * The setting ``ACCOUNT_ACTIVATION_DAYS`` be supplied, specifying
      (as an integer) the number of days from registration during
      which a user may activate their account (after that period
      expires, activation will be disallowed).

    * The creation of the templates
      ``registration/activation_email_subject.txt`` and
      ``registration/activation_email.txt``, which will be used for
      the activation email. See the notes for this backends
      ``register`` method for details regarding these templates.

    Additionally, registration can be temporarily closed by adding the
    setting ``REGISTRATION_OPEN`` and setting it to
    ``False``. Omitting this setting, or setting it to ``True``, will
    be interpreted as meaning that registration is currently open and
    permitted.

    Internally, this is accomplished via storing an activation key in
    an instance of ``registration.models.RegistrationProfile``. See
    that model and its custom manager for full documentation of its
    fields and supported operations.
    
    """
    def register(self, request, **cleaned_data):
        """
        Given a username, email address and password, register a new
        user account, which will initially be inactive.

        Along with the new ``User`` object, a new
        ``registration.models.RegistrationProfile`` will be created,
        tied to that ``User``, containing the activation key which
        will be used for this account.

        An email will be sent to the supplied email address; this
        email should contain an activation link. The email will be
        rendered using two templates. See the documentation for
        ``RegistrationProfile.send_activation_email()`` for
        information about these templates and the contexts provided to
        them.

        After the ``User`` and ``RegistrationProfile`` are created and
        the activation email is sent, the signal
        ``registration.signals.user_registered`` will be sent, with
        the new ``User`` as the keyword argument ``user`` and the
        class of this backend as the sender.

        """
        username, email, password = cleaned_data['username'], cleaned_data['email'], cleaned_data['password1']
        if Site._meta.installed:
            site = Site.objects.get_current()
        else:
            site = RequestSite(request)
        new_user = RegistrationProfile.objects.create_inactive_user(username, email,
                                                                    password, site)
        signals.user_registered.send(sender=self.__class__,
                                     user=new_user,
                                     request=request)
        return new_user

    def registration_allowed(self, request):
        """
        Indicate whether account registration is currently permitted,
        based on the value of the setting ``REGISTRATION_OPEN``. This
        is determined as follows:

        * If ``REGISTRATION_OPEN`` is not specified in settings, or is
          set to ``True``, registration is permitted.

        * If ``REGISTRATION_OPEN`` is both specified and set to
          ``False``, registration is not permitted.
        
        """
        return getattr(settings, 'REGISTRATION_OPEN', True)

    def get_success_url(self, request, user):
        """
        Return the name of the URL to redirect to after successful
        user registration.
        
        """
        return ('registration_complete', (), {})


class ActivationView(BaseActivationView):
    def activate(self, request, activation_key):
        """
        Given an an activation key, look up and activate the user
        account corresponding to that key (if possible).

        After successful activation, the signal
        ``registration.signals.user_activated`` will be sent, with the
        newly activated ``User`` as the keyword argument ``user`` and
        the class of this backend as the sender.
        
        """
        activated_user = RegistrationProfile.objects.activate_user(activation_key)
        if activated_user:
            signals.user_activated.send(sender=self.__class__,
                                        user=activated_user,
                                        request=request)
        return activated_user

    def get_success_url(self, request, user):
        return ('registration:registration_activation_complete', (), {})

accounts/backends/default/views.py
# -*- coding: utf-8 -*-
# 
# Copyright 2013 XiaoMaiFeng


__author__ = "ubernostrum "
__repo__ = "https://bitbucket.org/ubernostrum/django-registration/"
__editor__ = "Bicheng Zhang"
__copyright__ = "Copyright 2013, XiaoMaiFeng"


from django.conf import settings
from django.contrib.sites.models import RequestSite
from django.contrib.sites.models import Site
from django.core.urlresolvers import reverse
from django.contrib.auth import logout


from accounts import signals
from accounts.models import RegistrationProfile
from accounts.views import ActivationBaseView, RegistrationBaseView, DeActivationBaseView


class RegistrationView(RegistrationBaseView):
    """
    A registration backend which follows a simple workflow:

    1. User signs up, inactive account is created.

    2. Email is sent to user with activation link.

    3. User clicks activation link, account is now active.

    Using this backend requires that

    * ``registration`` be listed in the ``INSTALLED_APPS`` setting
      (since this backend makes use of models defined in this
      application).

    * The setting ``ACCOUNT_ACTIVATION_DAYS`` be supplied, specifying
      (as an integer) the number of days from registration during
      which a user may activate their account (after that period
      expires, activation will be disallowed).

    * The creation of the templates
      ``registration/activation_email_subject.txt`` and
      ``registration/activation_email.txt``, which will be used for
      the activation email. See the notes for this backends
      ``register`` method for details regarding these templates.

    Additionally, registration can be temporarily closed by adding the
    setting ``REGISTRATION_OPEN`` and setting it to
    ``False``. Omitting this setting, or setting it to ``True``, will
    be interpreted as meaning that registration is currently open and
    permitted.

    Internally, this is accomplished via storing an activation key in
    an instance of ``registration.models.RegistrationProfile``. See
    that model and its custom manager for full documentation of its
    fields and supported operations.
    
    """
    def register(self, request, **cleaned_data):
        """
        Given a username, email address and password, register a new
        user account, which will initially be inactive.

        Along with the new ``User`` object, a new
        ``registration.models.RegistrationProfile`` will be created,
        tied to that ``User``, containing the activation key which
        will be used for this account.

        An email will be sent to the supplied email address; this
        email should contain an activation link. The email will be
        rendered using two templates. See the documentation for
        ``RegistrationProfile.send_activation_email()`` for
        information about these templates and the contexts provided to
        them.

        After the ``User`` and ``RegistrationProfile`` are created and
        the activation email is sent, the signal
        ``registration.signals.user_registered`` will be sent, with
        the new ``User`` as the keyword argument ``user`` and the
        class of this backend as the sender.

        """
        username, email, password = cleaned_data['username'], cleaned_data['email'], cleaned_data['password1']
        if Site._meta.installed:
            site = Site.objects.get_current()
        else:
            site = RequestSite(request)
        new_user = RegistrationProfile.objects.create_inactive_user(username, email,
                                                                    password, site)
        signals.user_registered.send(sender=self.__class__,
                                     user=new_user,
                                     request=request)
        return new_user

    def registration_allowed(self, request):
        """
        Indicate whether account registration is currently permitted,
        based on the value of the setting ``REGISTRATION_OPEN``. This
        is determined as follows:

        * If ``REGISTRATION_OPEN`` is not specified in settings, or is
          set to ``True``, registration is permitted.

        * If ``REGISTRATION_OPEN`` is both specified and set to
          ``False``, registration is not permitted.
        
        """
        return getattr(settings, 'REGISTRATION_OPEN', True)

    def get_success_url(self, request, user):
        """
        Return the name of the URL to redirect to after successful
        user registration.
        
        """
        return ('accounts:registration_complete', (), {})


class ActivationView(ActivationBaseView):

    def activate(self, request, activation_key):
        """
        Given an an activation key, look up and activate the user
        account corresponding to that key (if possible).

        After successful activation, the signal
        ``registration.signals.user_activated`` will be sent, with the
        newly activated ``User`` as the keyword argument ``user`` and
        the class of this backend as the sender.
        
        """
        activated_user = RegistrationProfile.objects.activate_user(activation_key)
        if activated_user:
            signals.user_activated.send(sender=self.__class__,
                                        user=activated_user,
                                        request=request)
        return activated_user

    def get_success_url(self, request, user):
        return ('accounts:registration_activation_complete', (), {})




class ReActivationView(ActivationBaseView):

    def activate(self, request, *args, **kwargs):

        user = self.request.user
        
        user.is_active = True

        user.save()

        return user

    def get_success_url(self, request, user):
        return ('accounts:registration_activation_complete', (), {})



class DeActivationView(DeActivationBaseView):

    def get_redirect_url(self, **kwargs):
        """
        注销用户，设is_active to False,
        同时登出用户
        """
        user = self.request.user # 缓存用户

        user.is_active = False

        user.save()

        logout(self.request)

        return reverse('home:index') #TODO: redirect to cancel success page

accounts/templates/accounts/activate.html
{% extends "accounts/registration_base.html" %}
{% block title %}{% if account %}Activation complete{% else %}Activation problem{% endif %}{% endblock %}
{% block content %}
{% if account %}
Thanks {{ account }}, activation complete!  You may now <a href="{% url 'auth_login' %}">login</a> using the username and password you set at registration.
{% else %}
Oops &ndash; it seems that your activation key is invalid.  Please check the url again.
{% endif %}
{% endblock %}

accounts/templates/accounts/activation_complete.html
{% extends "accounts/registration_base.html" %}
{% block title %}Activation complete{% endblock %}
{% block content %}
Thanks, activation complete!  You may now <a href="{% url 'accounts:auth_login' %}">login</a> using the username and password you set at registration.
{% endblock %}

accounts/templates/accounts/base.html
{% load i18n %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
{% load staticfiles %}
<head>
    <link rel="stylesheet" href="{% static "css/reg_style.css" %}" />
	<meta charset="utf-8">
  	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>{% block title %}User test{% endblock %}</title>
</head>

<body>
    <div id="header">
        {% block header %}
	<a href="{% url 'home:index' %}">{% trans "主页" %}</a> | 

	{% if user.is_authenticated %}
	{% trans "Logged in" %}: {{ user.username }} 
	(<a href="{% url 'accounts:auth_logout' %}">{% trans "登出" %}</a> | 
	<a href="{% url 'accounts:auth_password_change' %}">{% trans "更改密码" %}</a>)
	{% else %}
	<a href="{% url 'accounts:auth_login' %}">{% trans "登入" %}</a>
	{% endif %}
	<hr />
        {% endblock %}
    </div>

    <section class="container">
        {% block content %}{% endblock %}
    </section>

    <div id="footer">
        {% block footer %}
        <hr />
        {% endblock %}
    </div>
</body>

</html>

accounts/templates/accounts/login.html
{% extends 'dashboard/base.html' %}
{% block dashboard_body %}


<div class="container-fluid">
	<div class="row-fluid">		
		<div class="row-fluid">
			<div class="login-box">
				<div class="icons">
					<a href="{% url 'home:index' %}"><i class="halflings-icon home"></i></a>
					<a href="#"><i class="halflings-icon cog"></i></a>
				</div>
				<h2>用户登陆</h2>
				<form class="form-horizontal" action="{% url 'accounts:auth_login' %}" method="post">{% csrf_token %}
					<fieldset>
						{{ form.non_field_errors }}
						<div class="input-prepend" title="Username">
							<span class="add-on"><i class="halflings-icon user"></i></span>
							{{ form.username }}
						</div>
						<div class="controls">{{form.username.errors}}</div>
						<div class="clearfix"></div>

						<div class="input-prepend" title="Password">
							<span class="add-on"><i class="halflings-icon lock"></i></span>
							{{ form.password }}
						</div>
						<div class="controls">{{form.password.errors}}</div>
						<div class="clearfix"></div>

						<div class="button-login">	
							<button type="submit" class="btn btn-primary">登陆</button>
						</div>
						<div class="clearfix"></div>
				</form>
				<hr>
				<p>
					<a href="{% url 'accounts:auth_password_reset' %}"><span>忘记密码</span></a>
					<a href="{% url 'accounts:registration_register' %}"><span>立即注册</span></a>
				</p>	
			</div><!--/span-->
		</div><!--/row-->
	</div><!--/fluid-row-->			
</div><!--/.fluid-container-->


{% endblock %}

accounts/templates/accounts/logout.html
{% extends "accounts/registration_base.html" %}
{% block title %}Logged out{% endblock %}
{% block content %}
Successfully logged out!
{% endblock %}

accounts/templates/accounts/password_change_done.html
{% extends "accounts/registration_base.html" %}
{% block title %}Password changed{% endblock %}
{% block content %}
Password successfully changed!
{% endblock %}

accounts/templates/accounts/password_change_form.html
{% extends "accounts/registration_base.html" %}
{% block title %}Change password{% endblock %}
{% block content %}
<form method='post' action=''>{% csrf_token %}
<table>
    {{ form }}
    <tr><td></td><td><input type='submit' value="Change password" /></td></tr>
</table>
</form>
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends "accounts/registration_base.html" %}
{% block title %}Password reset complete{% endblock %}
{% block content %}
Your password has been reset!  You may now <a href="{{ login_url }}">log in</a>.
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends "accounts/registration_base.html" %}
{% block title %}Confirm password reset{% endblock %}
{% block content %}
Enter your new password below to reset your password:
<form method="post" action="">{% csrf_token %}
<table>
    {{ form.as_table }}
    <tr><td></ td><td><input type="submit" value="Set password" /></td></tr>
</table>
</form>
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends "accounts/registration_base.html" %}
{% block title %}Password reset{% endblock %}
{% block content %}
<p>
We have sent you an email with a link to reset your password.  Please check
your email and click the link to continue.
</p>
{% endblock %}

accounts/templates/accounts/registration_base.html
{% extends "accounts/base.html" %}

accounts/templates/accounts/registration_closed.html
registration closed

accounts/templates/accounts/registration_complete.html
{% extends "accounts/registration_base.html" %}
{% block title %}Activation email sent{% endblock %}
{% block content %}
An activation email has been sent.  Please check your email and click on the link to activate your account.
{% endblock %}

accounts/templates/accounts/registration_form.html
{% extends "accounts/registration_base.html" %}
{% block title %}Register for an account{% endblock %}
{% block content %}
<div class="register">
<h1>用户注册</h1>
<table>
    <form method='post' action=''>{% csrf_token %}
        {{ form }}
        <tr><td></td><td><input type="submit" value="注册" /></td>
    </form>
</table>
<p>通过注册帐户您确认同意我们的<a href="{% url 'home:term' %}">使用守则</a></p>
</div>
{% endblock %}